<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.reinopixel</groupId>
    <artifactId>ServidorMMO</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- 
            NIO NETTY para la conexion evitando usar WEBSOCKETS 
        -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.100.Final</version>
        </dependency>

        <!-- 
            KCP para velocidad de UDP con TCP 
        -->
        <dependency>
            <groupId>io.jpower.kcp</groupId>
            <artifactId>kcp-netty</artifactId>
            <version>1.4.3</version>
        </dependency>
        <!-- 
            Librería para la encriptación segura de contraseñas (BCrypt) 
        -->
        <dependency>
            <groupId>org.mindrot</groupId>
            <artifactId>jbcrypt</artifactId>
            <version>0.4</version>
        </dependency>

        <!-- 
            Conector de base de datos PostgreSQL 
        -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.3</version>
        </dependency>

        <!-- 
            HikariCP: Pool de conexiones de alta eficiencia para PostgreSQL
        -->
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>5.1.0</version>
        </dependency>
  

        <!-- 
            SLF4J Simple: Motor de logs ligero.
            Soluciona el warning 'StaticLoggerBinder' de SLF4J
            y permite que herramientas como HikariCP impriman sus diagnósticos.
        -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.36</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- 
                maven-shade-plugin: Empaqueta nuestra aplicación junto con todas sus 
                dependencias en un único JAR ejecutable y define la clase principal.
            -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <!-- Clase principal que contiene el método main -->
                                    <mainClass>ServidorPrincipal</mainClass>
                                </transformer>
                            </transformers>
                            <!-- Soluciona problemas de firma con las librerías al empaquetar -->
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>